__version__ = "1.0.0"

import seaborn as sns
colors_tab10 = sns.color_palette("tab10")
colors = [colors_tab10[4], colors_tab10[3], colors_tab10[1], colors_tab10[2], colors_tab10[0]]
model_order = ['dlc', 'baseline', 'context', 'semi-super', 'semi-super context']
model_colors = {model: colors[i] for i, model in enumerate(model_order)}

dataset_info = {
    'mirror-mouse': {
        'skeleton': [],
    },
    'mirror-fish': {
        'skeleton': [
            ['chin_base_main', 'head_main'],
            ['chin1_4_main', 'chin_base_main'],
            ['chin_half_main', 'chin1_4_main'],
            ['chin3_4_main', 'chin_half_main'],
            ['chin_tip_main', 'chin3_4_main'],
            ['mid_main', 'head_main'],
            ['tail_neck_main', 'dorsal_main'],
            ['tail_neck_main', 'anal_main'],
            ['tail_neck_main', 'mid_main'],
            ['tail_neck_main', 'fork_main'],
            ['fork_main', 'caudal_d_main'],
            ['fork_main', 'caudal_v_main'],
            ['pectoral_L_main', 'pectoral_L_base_main'],
            ['pectoral_L_base_main', 'head_main'],
            ['pectoral_R_main', 'pectoral_R_base_main'],
            ['pectoral_R_base_main', 'head_main'],
            ['chin_base_top', 'head_top'],
            ['chin1_4_top', 'chin_base_top'],
            ['chin_half_top', 'chin1_4_top'],
            ['chin3_4_top', 'chin_half_top'],
            ['chin_tip_top', 'chin3_4_top'],
            ['mid_top', 'head_top'],
            ['tail_neck_top', 'dorsal_top'],
            ['tail_neck_top', 'anal_top'],
            ['tail_neck_top', 'mid_top'],
            ['tail_neck_top', 'fork_top'],
            ['fork_top', 'caudal_d_top'],
            ['fork_top', 'caudal_v_top'],
            ['pectoral_L_top', 'pectoral_L_base_top'],
            ['pectoral_L_base_top', 'head_top'],
            ['pectoral_R_top', 'pectoral_R_base_top'],
            ['pectoral_R_base_top', 'head_top'],
            ['chin_base_right', 'head_right'],
            ['chin1_4_right', 'chin_base_right'],
            ['chin_half_right', 'chin1_4_right'],
            ['chin3_4_right', 'chin_half_right'],
            ['chin_tip_right', 'chin3_4_right'],
            ['mid_right', 'head_right'],
            ['tail_neck_right', 'dorsal_right'],
            ['tail_neck_right', 'anal_right'],
            ['tail_neck_right', 'mid_right'],
            ['tail_neck_right', 'fork_right'],
            ['fork_right', 'caudal_d_right'],
            ['fork_right', 'caudal_v_right'],
            ['pectoral_L_right', 'pectoral_L_base_right'],
            ['pectoral_L_base_right', 'head_right'],
            ['pectoral_R_right', 'pectoral_R_base_right'],
            ['pectoral_R_base_right', 'head_right'],
        ],
    },
    'crim13': {
        'skeleton': [
            ['black_mouse_nose', 'black_mouse_right_ear'],
            ['black_mouse_nose', 'black_mouse_left_ear'],
            ['black_mouse_top_of_neck', 'black_mouse_right_ear'],
            ['black_mouse_top_of_neck', 'black_mouse_left_ear'],
            ['black_mouse_top_of_neck', 'black_mouse_right_rear_knee'],
            ['black_mouse_top_of_neck', 'black_mouse_left_rear_knee'],
            ['black_mouse_right_rear_knee', 'black_mouse_base_of_tail'],
            ['black_mouse_left_rear_knee', 'black_mouse_base_of_tail'],
            ['white_mouse_nose', 'white_mouse_right_ear'],
            ['white_mouse_nose', 'white_mouse_left_ear'],
            ['white_mouse_top_of_neck', 'white_mouse_right_ear'],
            ['white_mouse_top_of_neck', 'white_mouse_left_ear'],
            ['white_mouse_top_of_neck', 'white_mouse_right_rear_knee'],
            ['white_mouse_top_of_neck', 'white_mouse_left_rear_knee'],
            ['white_mouse_right_rear_knee', 'white_mouse_base_of_tail'],
            ['white_mouse_left_rear_knee', 'white_mouse_base_of_tail'],
        ],
    },
    'ibl-pupil': {
        'skeleton': [
            ['pupil_top_r', 'pupil_right_r'],
            ['pupil_right_r', 'pupil_bottom_r'],
            ['pupil_bottom_r', 'pupil_left_r'],
            ['pupil_left_r', 'pupil_top_r'],
        ],
    },
    'ibl-paw': {
        'skeleton': [],
    },
}
